#!/bin/bash

declare -a color
declare -a XCOLOR_OLD
declare -a XCOLOR_NEW

# Create array with old colors
for (( i = 0; i < 8; i++ )); do
	color[$i]="$(echo color$i)"
	XCOLOR_OLD[$i]="$(cat ~/.Xresources | grep -m 1 ${color[$i]} | awk '{print $2}')"
	echo ${XCOLOR_OLD[$i]}
done